# Generated by Django 5.1 on 2024-09-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_soft', '0002_alter_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
