# Generated by Django 5.1.1 on 2024-09-16 05:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_soft', '0003_manualreport_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualreport',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
