# Generated by Django 5.1.1 on 2024-09-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_soft', '0004_alter_manualreport_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualreport',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
