# Generated by Django 5.1.1 on 2024-09-18 04:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_soft', '0007_review_time_alter_review_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
